### ISSUE TITLE
Adding colours to connections like nodes

### ISSUE THREAD

**Issue by ghost** [ncase/loopy#19]
Hi, I sadly do not know much about css/js/html, however I am slowly starting to learn. I am working on a project with a friend at the minute and we would like to add colours to connections like you can with the nodes. Could you put me in the right direction in what to change to include this? Thanks. Ps really love the app it's so much more intuitive than anything similar.

**Comment by 1000i100** [comment]
I've tried to do this for other reasons : https://bit.ly/2TEQmpx
Does it do the job ?
If you want to look at the code, here it is : https://github.com/1000i100/loopy/commit/df57578f58f7d539c920a5bb3bce7d1c7384a5c9#diff-15b5aede4095d96c39cdaec581f7aebfR402

**Comment by 1000i100** [comment]
PS : if #20 is merged perhapse this issue can be closed ?
