### ISSUE TITLE
Load pre-generated model

### ISSUE THREAD

**Issue by bgyori** [ncase/loopy#5]
It would be great if an initial model generated by an outside tool could be loaded in Loopy. A user could then manually modify and simulate the initial model through the Loopy UI. Is there some data format in which one could pass an initial model to Loopy?

**Comment by bgyori** [comment]
Figured it out.

**Comment by Ryuno-Ki** [comment]
Would you mind to share the solution, @bgyori?

**Comment by bgyori** [comment]
When you make a model, the whole model is encoded in the URL as a data=[...] parameter. It's easy to figure out how entries in there correspond to model parts. But looking at the code here also helps: https://github.com/ncase/loopy/blob/gh-pages/v1/js/Model.js#L245-L324

**Comment by Ryuno-Ki** [comment]
Thanks
