### ISSUE TITLE
[feature-request] zoom out 

### ISSUE THREAD

**Issue by denistsoi** [ncase/loopy#6]
zooming out, i.e. via browser isn't supported.
Creating system flows that require more than say, ten nodes (which is the current maximum capacity of the current canvas)

**Comment by Seanny123** [comment]
Being able to pan the canvas would probably also help with this.

**Comment by ultimape** [comment]
This also would require a more effective saving mechanism as it quickly runs into the limits of how much data can be stored in the URL.

**Comment by merspieler** [comment]
For data, which is too long for the URL (the max length is different in different browsers), the user could be prompted to copy a string out of a text field (like in cookie clicker) and to save it, e.g. in a text file, of let the user download a text file which he/she has to upload when loading again.

**Comment by Ryuno-Ki** [comment]
I wonder, whether [createObjectURL](https://developer.mozilla.org/de/docs/Web/API/URL/createObjectURL) would help here …

**Comment by cbarina** [comment]
This also would help with longer text in the nodes - you can zoom in/out to read as some things need more than a word or two :)

**Comment by xklech** [comment]
@ncase We have quite big models we would like to persist and simulate and as stated in this issue area is too small. 

What I was thinking about was to use something like http://ianli.github.io/jquery-infinite-drag/ or something similar so u can move around the model. I tried it but I somehow got stuck that I somehow got the feeling that almost everything is bound to Browser window size. Boundaries for canvas, etc. 

Do you have please some advice about where to start looking? Or some other ideas about how to achieve bigger models now we have persistent storage possibility?

**Comment by 1000i100** [comment]
I'm planning to improve it (zoom on mouse position), but you can now zoom in/out and pan in #20 : https://1000i100.github.io/loopy/2/

**Comment by 1000i100** [comment]
zoom finalized and camera mode added.

**Comment by 1000i100** [comment]
@xklech does actual zoom and move do the job for your use-case ?

@denistsoi if it does what you want, you probably can close the issue (even if it will not be merged here but still maintained in my fork).
